/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import com.jtattoo.plaf.aluminium.AluminiumLookAndFeel;
import java.awt.FlowLayout;
import javax.swing.JFrame;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import javax.swing.JOptionPane;

/**
 *
 * @author Shidqi
 */
public class BiodataSaya extends javax.swing.JFrame {

    /**
     * Creates new form BiodataSaya
     */
    public BiodataSaya() {
        initComponents();
        setTitle("Dibuat Oleh Muhammad Shidqi");
        setExtendedState(getExtendedState()|JFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        fillHari();
        fillBulan();
        fillTahun();
        
        fillFakultas();
    }
    
    public static void tema(){
        try{
            /*
             * Pada UIManager kalian bisa memilih jenis tema
             * apa yang digunakan, sebagai contoh saya
             * menggunakan tema BernsteinLookAndFeel
            */
            UIManager.setLookAndFeel(new AluminiumLookAndFeel());
        }catch(UnsupportedLookAndFeelException ex){
            ex.printStackTrace();
        }
    }
    
    // Variabel Global fakultas di dalam class BiodataSaya
    static String fakultas[] = {
        "Syariah dan Hukum", "Tarbiyah", "Ushuluddin Dan Pemikiran Islam", "Adab Dan Humaniora",
        "Dakwah Dan Komunikasi", "Ekonomi Dan Bisnis Islam", "Ilmu Sosial Dan Ilmu Politik",
        "Psikologi", "Sains Dan Teknologi"
    };
    
    // Variabel Global jurusan 2 Dimensi di dalam class BiodataSaya
    static String jurusan[][] = {
        {
            "Jinayah Siyasah / Pidana dan politik",
            "Perbandingan Mazhab dan Hukum",
            "Zakat dan Wakaf",
            "Mu’amalah / Perdata dan Niaga",
            "Al-Akhwal al-Syakhsiyah / Hukum Keluarga"
        },
        {
            "Manajemen Pendidikan Islam",
            "Pendidikan Bahasa Arab",
            "Pendidikan Guru Madrasah Ibtidaiyah",
            "Pendidikan Bahasa Inggris",
            "Pendidikan Guru Raudhatul Athfal",
            "Pendidikan Biologi",
            "Pendidikan Matematika",
            "Pendidikan Kimia",
            "Pendidikan Fisika",
            "Pendidikan Agama Islam"
        },
        {
            "Aqidah Filsafat Islam",
            "Ilmu Hadist",
            "Tasawuf dan Psikoterapi",
            "Ilmu Al-Qur’an dan Tafsir",
            "Studi Agama-Agama"
        },
        {
            "Sejarah dan Kebudayaan Islam",
            "Bahasa dan Sastra Arab",
            "Ilmu Perpustakaan",
            "Politik Islam"
        },
        {
            "Jurnalistik",
            "Bimbingan dan Penyuluhan Islam",
            "Pengembangan Masyarakat Islam",
            "Manajemen Dakwah",
            "Komunikasi dan Penyiaran Islam"
        },
        {
            "D3 Perbankan Syari ah",
            "Perbankan Syari ah",
            "Ekonomi Islam"
        },
        {
            "Ilmu Komunikasi",
            "Ilmu Politik"
        },
        {
            "Psikologi Islam"
        },
        {
            "Sistem Informasi",
            "Kimia",
            "Biologi"
        }
    };
    
    public void fillFakultas() {
        for (int i = 0; i < fakultas.length; i++) {
            comboFakultas.addItem(fakultas[i]);
        }
    }
    
    public void fillJurusan(int index) {
        // menghapus seluruh isi combo box jurusan
        comboJurusan.removeAllItems();
        
        // hanya mengambil data dari index yang di kirimkan oleh fakultas
                                // index merupakan pemilih untuk golongan fakultas di jurusan
        for (int i = 0; i < jurusan[index].length; i++) {
            comboJurusan.addItem(jurusan[index][i]);
        }
    }
    
    public void fillHari() {
        int i;
        for (i = 1; i <= 31; i++) {
            comboHari.addItem(i);
        }
    }
    
    public void fillBulan() {
        int i;
        for (i = 1; i <= 12; i++) {
            comboBulan.addItem(i);
        }
    }
    
    public void fillTahun() {
        int i;
        for (i = 1920; i <= 2020; i++) {
            comboTahun.addItem(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bgJK = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        radioLaki = new javax.swing.JRadioButton();
        radioPerempuan = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        comboHari = new javax.swing.JComboBox<>();
        comboBulan = new javax.swing.JComboBox<>();
        comboTahun = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        comboKota = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNim = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtHobi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtLahir = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNamaAyah = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPekerjaanAyah = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtNamaIbu = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtPekerjaanIbu = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtTelp = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        comboJurusan = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        comboFakultas = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuKalkulator = new javax.swing.JMenuItem();
        menuBerat = new javax.swing.JMenuItem();
        menuBiodata = new javax.swing.JMenuItem();
        menuRumahMakan = new javax.swing.JMenuItem();
        menuPembayaran = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        logOut = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 680));
        setPreferredSize(new java.awt.Dimension(1100, 680));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Biodata Saya");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 75;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 140, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 66;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 163;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 28, 0, 0);
        getContentPane().add(txtName, gridBagConstraints);

        jLabel2.setText("Nama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("Jenis Kelamin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        bgJK.add(radioLaki);
        radioLaki.setText("Laki Laki");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 28, 0, 0);
        getContentPane().add(radioLaki, gridBagConstraints);

        bgJK.add(radioPerempuan);
        radioPerempuan.setText("Perempuan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 41;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 4, 0, 0);
        getContentPane().add(radioPerempuan, gridBagConstraints);

        jLabel4.setText("Tanggal Lahir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 10, 0, 0);
        getContentPane().add(jLabel4, gridBagConstraints);

        comboHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboHariActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 27;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 28, 0, 0);
        getContentPane().add(comboHari, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 27;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 0, 0);
        getContentPane().add(comboBulan, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 32;
        gridBagConstraints.gridy = 27;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 20, 0, 0);
        getContentPane().add(comboTahun, gridBagConstraints);

        jLabel5.setText("Alamat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 33;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 10, 0, 0);
        getContentPane().add(jLabel5, gridBagConstraints);

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 33;
        gridBagConstraints.gridwidth = 24;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.ipady = 73;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(9, 28, 0, 0);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jLabel6.setText("Kota Sekarang");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 35;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 10, 0, 0);
        getContentPane().add(jLabel6, gridBagConstraints);

        comboKota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Hari --", "Palembang", "Jakarta", "Jambi", "Padang" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 35;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 28, 0, 0);
        getContentPane().add(comboKota, gridBagConstraints);

        hasil.setColumns(20);
        hasil.setRows(5);
        jScrollPane2.setViewportView(hasil);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 83;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 37;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 307;
        gridBagConstraints.ipady = 467;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 60, 0, 17);
        getContentPane().add(jScrollPane2, gridBagConstraints);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 75;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 130, 0, 0);
        getContentPane().add(btnSimpan, gridBagConstraints);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 75;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 130, 0, 0);
        getContentPane().add(btnHapus, gridBagConstraints);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 75;
        gridBagConstraints.gridy = 29;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 130, 0, 0);
        getContentPane().add(btnKeluar, gridBagConstraints);

        jLabel7.setText("Hari");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 28, 0, 0);
        getContentPane().add(jLabel7, gridBagConstraints);

        jLabel8.setText("Bulan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 7, 0, 0);
        getContentPane().add(jLabel8, gridBagConstraints);

        jLabel9.setText("Tahun");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 32;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.gridwidth = 42;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 20, 0, 0);
        getContentPane().add(jLabel9, gridBagConstraints);

        jLabel10.setText("NIM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(jLabel10, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 66;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 163;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 28, 0, 0);
        getContentPane().add(txtNim, gridBagConstraints);

        jLabel11.setText("Hobi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 75;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 130, 0, 0);
        getContentPane().add(jLabel11, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 81;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(txtHobi, gridBagConstraints);

        jLabel12.setText("Tempat Kelahiran");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 10, 0, 0);
        getContentPane().add(jLabel12, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 103;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 28, 0, 0);
        getContentPane().add(txtLahir, gridBagConstraints);

        jLabel13.setText("Orang Tua:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 75;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 130, 0, 0);
        getContentPane().add(jLabel13, gridBagConstraints);

        jLabel14.setText("Nama Ayah");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 75;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 130, 0, 0);
        getContentPane().add(jLabel14, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 81;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 0, 0);
        getContentPane().add(txtNamaAyah, gridBagConstraints);

        jLabel15.setText("Pekerjaan Ayah");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 75;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 130, 0, 0);
        getContentPane().add(jLabel15, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 81;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 10, 0, 0);
        getContentPane().add(txtPekerjaanAyah, gridBagConstraints);

        jLabel16.setText("Nama Ibu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 75;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 130, 0, 0);
        getContentPane().add(jLabel16, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 81;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 10, 0, 0);
        getContentPane().add(txtNamaIbu, gridBagConstraints);

        jLabel17.setText("Pekerjaan Ibu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 75;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 130, 0, 0);
        getContentPane().add(jLabel17, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 81;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        getContentPane().add(txtPekerjaanIbu, gridBagConstraints);

        jLabel18.setText("No. Telepon");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 37;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 38;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 10, 0, 0);
        getContentPane().add(jLabel18, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 37;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.gridheight = 39;
        gridBagConstraints.ipadx = 113;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 28, 63, 0);
        getContentPane().add(txtTelp, gridBagConstraints);

        jLabel19.setText("Jurusan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 0, 0);
        getContentPane().add(jLabel19, gridBagConstraints);

        comboJurusan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboJurusanItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 28, 0, 0);
        getContentPane().add(comboJurusan, gridBagConstraints);

        jLabel20.setText("Fakultas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 0, 0);
        getContentPane().add(jLabel20, gridBagConstraints);

        comboFakultas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFakultasItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 28, 0, 0);
        getContentPane().add(comboFakultas, gridBagConstraints);

        jMenu1.setText("File");

        menuKalkulator.setText("Kalkulator Sederhana");
        menuKalkulator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKalkulatorActionPerformed(evt);
            }
        });
        jMenu1.add(menuKalkulator);

        menuBerat.setText("Berat Badan Ideal");
        menuBerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBeratActionPerformed(evt);
            }
        });
        jMenu1.add(menuBerat);

        menuBiodata.setText("Biodata");
        menuBiodata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBiodataActionPerformed(evt);
            }
        });
        jMenu1.add(menuBiodata);

        menuRumahMakan.setText("Rumah Makan");
        menuRumahMakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRumahMakanActionPerformed(evt);
            }
        });
        jMenu1.add(menuRumahMakan);

        menuPembayaran.setText("Pembayaran");
        menuPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPembayaranActionPerformed(evt);
            }
        });
        jMenu1.add(menuPembayaran);

        jMenuItem1.setText("Form Mahasiswa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        logOut.setText("Logout");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        jMenu1.add(logOut);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboHariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboHariActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String kesimpulan = "Biodata Anda:\n";
        kesimpulan += "\nNIM: "+ txtNim.getText();
        kesimpulan += "\nNama : " + txtName.getText();
        
        String Jk=" ";
        if (radioLaki.isSelected()==true) Jk="Laki-laki";
        else
        if (radioPerempuan.isSelected()==true) Jk="Perempuan";
        
        kesimpulan += "\nJenis Kelamin: "+Jk;
        kesimpulan += "\nFakultas: "+ comboFakultas.getSelectedItem();
        kesimpulan += "\nJurusan: "+ comboJurusan.getSelectedItem();
        
        kesimpulan += "\n";

        kesimpulan += "\nTempat Kelahiran: "+ txtLahir.getText();
        kesimpulan += "\nTanggal: "+comboHari.getSelectedItem(); 
        kesimpulan += "/ "+comboBulan.getSelectedItem(); 
        kesimpulan += "/ "+comboTahun.getSelectedItem();
        kesimpulan += "\nAlamat: "+ txtAlamat.getText();
        kesimpulan += "\nKota: "+comboKota.getSelectedItem();
        kesimpulan += "\nNomor Telepon: "+ txtTelp.getText();
        
        kesimpulan += "\n";
        
        kesimpulan += "\nHobi: "+ txtHobi.getText();
        kesimpulan += "\nOrang Tua";
        kesimpulan += "\nNama Ayah: "+ txtNamaAyah.getText();
        kesimpulan += "\nPekerjaan Ayah: "+ txtPekerjaanAyah.getText();
        kesimpulan += "\nNama Ibu: "+ txtNamaIbu.getText();
        kesimpulan += "\nPekerjaan Ibu: "+ txtPekerjaanIbu.getText();
        
        txtName.requestFocus();
        hasil.setText(kesimpulan);

        JOptionPane.showMessageDialog(null,"Data Berhasil di Simpan ");

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        txtName.setText(" ");
        bgJK.clearSelection();
        comboHari.setSelectedIndex(-1);
        comboBulan.setSelectedIndex(-1);
        comboTahun.setSelectedIndex(-1);
        txtAlamat.setText(" ");
        
        txtNim.setText(" ");
        txtHobi.setText(" ");
        txtLahir.setText(" ");
        txtNamaAyah.setText(" ");
        txtPekerjaanAyah.setText(" ");
        txtNamaIbu.setText(" ");
        txtPekerjaanIbu.setText(" ");
        
        txtTelp.setText(" ");
        comboJurusan.setSelectedIndex(-1);
        comboFakultas.setSelectedIndex(-1);
      
        hasil.setText(" ");
        comboKota.setSelectedIndex(-1);
        txtName.requestFocus();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null,
        "Apakah anda akan menutup system?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
                                         // Menggunakan Sistem Yes No Option yang ada pada class JOoptionPane

        if (selectedOption == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void comboJurusanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboJurusanItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboJurusanItemStateChanged

    private void comboFakultasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboFakultasItemStateChanged
        // TODO add your handling code here:
        
        /* 
            jika combo fakultas di ubah, maka akan menjalan kan method jurusan dengan mengirimkan
            sebuah parameter berupa index dari combo box fakultas yang di pilih 
        */
        
        fillJurusan(comboFakultas.getSelectedIndex());
    }//GEN-LAST:event_comboFakultasItemStateChanged

    private void menuKalkulatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKalkulatorActionPerformed
        // TODO add your handling code here:
        new FormKalkulator().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuKalkulatorActionPerformed

    private void menuBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBeratActionPerformed
        // TODO add your handling code here:
        new FormBeratBadan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuBeratActionPerformed

    private void menuBiodataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBiodataActionPerformed
        // TODO add your handling code here:
        new BiodataSaya().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuBiodataActionPerformed

    private void menuRumahMakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRumahMakanActionPerformed
        // TODO add your handling code here:
        new RumahMakanAntiGalau().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuRumahMakanActionPerformed

    private void menuPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPembayaranActionPerformed
        // TODO add your handling code here:
        new FormPembayaran().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuPembayaranActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new FormMahasiswa().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        new FormLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logOutActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null,
            "Apakah anda akan menutup system?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
        // Menggunakan Sistem Yes No Option yang ada pada class JOoptionPane

        if (selectedOption == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiodataSaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiodataSaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiodataSaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiodataSaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        tema();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiodataSaya().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgJK;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<Integer> comboBulan;
    private javax.swing.JComboBox<String> comboFakultas;
    private javax.swing.JComboBox<Integer> comboHari;
    private javax.swing.JComboBox<String> comboJurusan;
    private javax.swing.JComboBox<String> comboKota;
    private javax.swing.JComboBox<Integer> comboTahun;
    private javax.swing.JMenuItem exit;
    private javax.swing.JTextArea hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem logOut;
    private javax.swing.JMenuItem menuBerat;
    private javax.swing.JMenuItem menuBiodata;
    private javax.swing.JMenuItem menuKalkulator;
    private javax.swing.JMenuItem menuPembayaran;
    private javax.swing.JMenuItem menuRumahMakan;
    private javax.swing.JRadioButton radioLaki;
    private javax.swing.JRadioButton radioPerempuan;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtHobi;
    private javax.swing.JTextField txtLahir;
    private javax.swing.JTextField txtNamaAyah;
    private javax.swing.JTextField txtNamaIbu;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtPekerjaanAyah;
    private javax.swing.JTextField txtPekerjaanIbu;
    private javax.swing.JTextField txtTelp;
    // End of variables declaration//GEN-END:variables
}
