/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import com.jtattoo.plaf.aero.AeroLookAndFeel;
import com.jtattoo.plaf.aluminium.AluminiumLookAndFeel;
import com.jtattoo.plaf.bernstein.BernsteinLookAndFeel;
import com.jtattoo.plaf.hifi.HiFiLookAndFeel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.metal.MetalLookAndFeel;

/**
 *
 * @author Shidqi
 */
public class FormBeratBadan extends javax.swing.JFrame {

    /**
     * Creates new form FormBeratBadan
     */
    public FormBeratBadan() {
        initComponents();
        setTitle("Muhammad Shidqi");
        setExtendedState(getExtendedState()|JFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    
    public static void tema(){
        try{
            /*
             * Pada UIManager kalian bisa memilih jenis tema
             * apa yang digunakan, sebagai contoh saya
             * menggunakan tema BernsteinLookAndFeel
            */
            UIManager.setLookAndFeel(new AluminiumLookAndFeel());
        }catch(UnsupportedLookAndFeelException ex){
            ex.printStackTrace();
        }
    }
    
    public void ideal(){
        double tinggi, ideal;
        
        tinggi = Double.parseDouble(txt_tinggi.getText());
        
        ideal = ((tinggi - 100) * 90)/100;
        
        lbl_ideal.setText(String.valueOf(ideal));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_tinggi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbl_ideal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuKalkulator = new javax.swing.JMenuItem();
        menuBerat = new javax.swing.JMenuItem();
        menuBiodata = new javax.swing.JMenuItem();
        menuRumahMakan = new javax.swing.JMenuItem();
        menuPembayaran = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        logOut = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Berat Badan Ideal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 60, 0, 53);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Tinggi Badan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 30, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        txt_tinggi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_tinggiKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 60, 0, 0);
        getContentPane().add(txt_tinggi, gridBagConstraints);

        jLabel3.setText("Berat Badan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 30, 85, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        lbl_ideal.setText("....");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 60, 85, 0);
        getContentPane().add(lbl_ideal, gridBagConstraints);

        jMenu1.setText("File");

        menuKalkulator.setText("Kalkulator Sederhana");
        menuKalkulator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKalkulatorActionPerformed(evt);
            }
        });
        jMenu1.add(menuKalkulator);

        menuBerat.setText("Berat Badan Ideal");
        menuBerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBeratActionPerformed(evt);
            }
        });
        jMenu1.add(menuBerat);

        menuBiodata.setText("Biodata");
        menuBiodata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBiodataActionPerformed(evt);
            }
        });
        jMenu1.add(menuBiodata);

        menuRumahMakan.setText("Rumah Makan");
        menuRumahMakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRumahMakanActionPerformed(evt);
            }
        });
        jMenu1.add(menuRumahMakan);

        menuPembayaran.setText("Pembayaran");
        menuPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPembayaranActionPerformed(evt);
            }
        });
        jMenu1.add(menuPembayaran);

        jMenuItem1.setText("Form Mahasiswa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        logOut.setText("Logout");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        jMenu1.add(logOut);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tinggiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tinggiKeyReleased
        // TODO add your handling code here:
        ideal();
    }//GEN-LAST:event_txt_tinggiKeyReleased

    private void menuKalkulatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKalkulatorActionPerformed
        // TODO add your handling code here:
        new FormKalkulator().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuKalkulatorActionPerformed

    private void menuBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBeratActionPerformed
        // TODO add your handling code here:
        new FormBeratBadan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuBeratActionPerformed

    private void menuBiodataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBiodataActionPerformed
        // TODO add your handling code here:
        new BiodataSaya().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuBiodataActionPerformed

    private void menuRumahMakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRumahMakanActionPerformed
        // TODO add your handling code here:
        new RumahMakanAntiGalau().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuRumahMakanActionPerformed

    private void menuPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPembayaranActionPerformed
        // TODO add your handling code here:
        new FormPembayaran().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuPembayaranActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new FormMahasiswa().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        new FormLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logOutActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null,
            "Apakah anda akan menutup system?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
        // Menggunakan Sistem Yes No Option yang ada pada class JOoptionPane

        if (selectedOption == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBeratBadan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBeratBadan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBeratBadan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBeratBadan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        tema();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBeratBadan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lbl_ideal;
    private javax.swing.JMenuItem logOut;
    private javax.swing.JMenuItem menuBerat;
    private javax.swing.JMenuItem menuBiodata;
    private javax.swing.JMenuItem menuKalkulator;
    private javax.swing.JMenuItem menuPembayaran;
    private javax.swing.JMenuItem menuRumahMakan;
    private javax.swing.JTextField txt_tinggi;
    // End of variables declaration//GEN-END:variables
}
